# Generated by Django 5.2.13 on 2026-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_headline_company_established_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
