# Generated by Django 4.2.7 on 2026-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0013_job_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
    ]
