# Generated by Django 5.2.13 on 2026-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0016_remove_experience_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Addis Ababa', max_length=150),
        ),
    ]
