# Generated by Django 5.2.13 on 2026-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0018_alter_job_created_at_alter_job_filled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
