# Generated by Django 5.2.13 on 2026-09-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0019_job_featured_until_job_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True),
        ),
    ]
